export const SETTINGS_TOGGLE = 'SETTINGS_TOGGLE';

export const ADD_TODO = 'ADD_TODO';

export const EDIT_TODO_TITLE = 'EDIT_TODO_TITLE';
export const EDIT_INPROGRESS_TITLE = "EDIT_INPROGRESS_TITLE";
export const EDIT_COMPLETED_TITLE = "EDIT_COMPLETED_TITLE";
