export const SETTINGS_TOGGLE = 'SETTINGS_TOGGLE';
export const SETTINGS_SAVE = 'SETTINGS_SAVE';

export const ADD_TODOS = 'ADD_TODO';
export const ADD_IN_PROGRESS = 'ADD_IN_PROGRESS';
export const ADD_COMPLETED = 'ADD_COMPLETED';

export const START_TODOS = 'START_TODO';
export const FINISH_IN_PROGRESS = 'FINISH_IN_PROGRESS';
export const ARCHIVE_COMPLETED = 'ARCHIVE_COMPLETED';

export const EDIT_TASK = 'EDIT_TASK';
export const DELETE_TASK = 'DELETE_TASK';
