export const SETTINGS_TOGGLE = 'SETTINGS_TOGGLE';

export const ADD_TODO = 'ADD_TODO';
export const ADD_IN_PROGRESS = 'ADD_IN_PROGRESS';
export const ADD_COMPLETED = 'ADD_COMPLETED';

export const START_TODO = 'START_TODO';
export const FINISH_IN_PROGRESS = 'FINISH_IN_PROGRESS';
export const ARCHIVE_COMPLETED = 'ARCHIVE_COMPLETED';

export const EDIT_TODO_TITLE = 'EDIT_TODO_TITLE';
export const EDIT_IN_PROGRESS_TITLE = 'EDIT_INPROGRESS_TITLE';
export const EDIT_COMPLETED_TITLE = 'EDIT_COMPLETED_TITLE';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_IN_PROGRESS = 'DELETE_IN_PROGRESS';
export const DELETE_COMPLETED = 'DELETE_COMPLETED';
